config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  resources :hotels
  resources :dashboards, only: :index
  resources :available_rooms, only: :index
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms
end

app/models/room.rb
class Room < ApplicationRecord
  CATEGORIES = %i[
    standart
    lux
  ].freeze

  belongs_to :hotel, optional: true

  has_many :bookings

  scope :available, ->(from, till, city) { joins(:hotel).merge(Hotel.where(city: city)).exclude(Room.joins(:bookings).merge(Booking.where(date: from..till))) }
  scope :exclude, ->(ids) { where.not(id: ids) }
  enum category: CATEGORIES
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/available_rooms_controller.rb
class AvailableRoomsController < ApplicationController
  helper_method :rooms

  private

  def rooms
    @rooms ||= Room.available(Date.parse(params[:from]), Date.parse(params[:till]), params[:city])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = current_user.bookings.order(date: :desc)
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    from = Date.parse(booking_params.delete(:from))
    till = Date.parse(booking_params.delete(:till))

    (from..till).each do |date|
      Booking.create!(**booking_params.slice(:user_id, :room_id), date: date)
    end

    respond_to do |format|
      format.html { redirect_to bookings_path, notice: "Bookings were successfully created." }
      format.json { render :show, status: :created, location: @booking }
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully canceled." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.permit(:user_id, :room_id, :from, :till)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :address)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:hotel_id, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/available_rooms/index.html.erb
<br>

<table class="table">
  <thead>
  <tr>
    <th colpan="5">Hotel</th>
    <th>City</th>
    <th>Category</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% rooms.each do |room| %>
    <tr>
      <td><%= room.hotel.name %></td>
      <td><%= room.hotel.city %></td>
      <td><%= room.category.upcase %></td>
      <td><%= link_to 'Book', bookings_path(room_id: room, user_id: current_user, from: params[:from], till: params[:till]), method: :post, class: "btn btn-success #{"disabled" unless user_signed_in?}", disabled: !user_signed_in? %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/bookings/_form.html.erb
<%= form_for(@booking, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @booking.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h4>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :room, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :room, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="page-header">
  <%= link_to bookings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @booking, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing booking</h1>
</div>

<%= render 'form' %>

app/views/bookings/index.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>
<div class="page-header">
  <h1>Listing bookings</h1>
</div>

<div>
  <table class="table">
    <thead>
    <tr>
      <th>Hotel</th>
      <th>Room</th>
      <th>Date</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.room.hotel.name %></td>
        <td><%= booking.room.category.upcase %></td>
        <td><%= l(booking.date) %></td>
        <td><%= link_to 'Cancel booking', booking_path(booking), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/new.html.erb
<div class="page-header">
  <%= link_to bookings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New booking</h1>
</div>

<%= render 'form' %>

app/views/bookings/show.html.erb
<div class="page-header">
  <%= link_to bookings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_booking_path(@booking), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show booking</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @booking.user %></dd>

  <dt>Room:</dt>
  <dd><%= @booking.room %></dd>

</dl>

app/views/dashboards/index.html.erb
<% provide(:title, 'Home') %>

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Book a room for your favourite pet</h1>
        <div class="alert alert-dark">
        <%= form_tag(available_rooms_path, :method => "get", id: "search-form") do %>
          <div class="row">
            <div class="col">
              <%= label_tag :city %>
              <%= text_field_tag :city, nil, placeholder: 'e.g. Lviv' %>
            </div>
            <div class="col">
              <%= label_tag :from %>
              <%= date_field_tag :from %>
            </div>
            <div class="col">
              <%= label_tag :till %>
              <%= date_field_tag :till %>
            </div>
            <div class="col">
              <%= submit_tag "Search", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.address %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <% if user_signed_in? %>
    <small>You`re succesfully logged in. <%= link_to 'Logout', destroy_user_session_url, :method => :delete %></small>
  <% else %>
    <small>To book a room you must be <%= link_to 'logged in', new_user_session_url %>. Not registered
      yet? <%= link_to 'Sign up.', new_user_registration_url %></small>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Pets sweet dream", root_url, id: "logo", class: "navbar-brand"%>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_url, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My bookings", bookings_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item pull-right">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_url, :method => :delete, class: "nav-link" %>
          <% else %>
            <%= link_to "Sign in", new_user_session_url, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>


<!--<nav class="navbar navbar-fixed-top navbar-inverse">-->
<!--  <div class="navbar-inner">-->
<!--    <div class="container">-->
      <%#= link_to "Pets sweet dream", root_url, id: "logo" %>
<!--      <nav>-->
<!--        <ul class="nav pull-right">-->
<!--          <li><%#= link_to "Home", root_url %></li>-->
<!--          <li><%#= link_to "My bookings", trips_url %></li>-->
          <%# if user_signed_in? %>
<!--            <li><%#= link_to "Profile", profile_url %></li>-->
<!--            <li><%#= link_to "Sign out", destroy_user_session_url, :method => :delete %></li>-->
          <%# else %>
<!--            <li><%#= link_to "Sign in", new_user_session_url %></li>-->
          <%# end %>
<!--        </ul>-->
<!--      </nav>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsSweetDream</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    </body>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hotel_id %>
    <%= form.text_field :hotel_id %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.number_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Hotel</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.hotel.name %></td>
        <td><%= room.category.upcase %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hotel:</strong>
  <%= @room.hotel_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @room.category %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>